/*
 * File: app/view/loginView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.loginView', {
    extend: 'Ext.window.Window',

    height: 250,
    id: 'loginView',
    width: 400,
    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    layout: {
                        type: 'auto'
                    },
                    bodyPadding: 10,
                    title: 'My Form',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            id: 'userName',
                            fieldLabel: 'user',
                            name: 'userName'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            id: 'userPass',
                            fieldLabel: 'password',
                            name: 'userPass'
                        },
                        {
                            xtype: 'button',
                            id: 'btnLogin',
                            text: 'Login'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});