/*
 * File: app/view/twitchView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.twitchView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.twitchView',

    id: 'twitchView',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    title: 'Twitch.tv',
                    items: [
                        {
                            xtype: 'container',
                            cls: 'col_left',
                            items: [
                                {
                                    xtype: 'label',
                                    cls: 'title',
                                    text: 'twitch'
                                },
                                {
                                    xtype: 'menu',
                                    cls: 'menu_simple',
                                    floating: false,
                                    items: [
                                        {
                                            xtype: 'menuitem',
                                            text: 'Menu Item'
                                        },
                                        {
                                            xtype: 'menuitem',
                                            text: 'Menu Item'
                                        },
                                        {
                                            xtype: 'menuitem',
                                            text: 'Menu Item'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'menu',
                                    cls: 'menu_simple',
                                    floating: false,
                                    items: [
                                        {
                                            xtype: 'menuitem',
                                            text: 'Menu Item'
                                        },
                                        {
                                            xtype: 'menuitem',
                                            text: 'Menu Item'
                                        },
                                        {
                                            xtype: 'menuitem',
                                            text: 'Menu Item'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'menu',
                                    cls: 'menu_simple',
                                    floating: false,
                                    items: [
                                        {
                                            xtype: 'menuitem',
                                            text: 'Menu Item'
                                        },
                                        {
                                            xtype: 'menuitem',
                                            text: 'Menu Item'
                                        },
                                        {
                                            xtype: 'menuitem',
                                            text: 'Menu Item'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            cls: 'col_center',
                            items: [
                                {
                                    xtype: 'dataview',
                                    cls: 'video',
                                    tpl: [
                                        '<object type="application/x-shockwave-flash" height="300" width="400" data="http://www.twitch.tv/widgets/live_embed_player.swf?channel=antenadota"><param name="movie" value="http://www.twitch.tv/widgets/live_embed_player.swf?channel=antenadota"></param><param name="allowScriptAccess" value="always"></param><param name="allowNetworking" value="all"></param><param name="allowFullScreen" value="true"></param><param name="flashvars" value="hostname=www.twitch.tv&start_volume=25&channel=antenadota&auto_play=false"></param></object>'
                                    ],
                                    itemSelector: 'div'
                                },
                                {
                                    xtype: 'container',
                                    cls: 'button_group_video'
                                },
                                {
                                    xtype: 'container'
                                },
                                {
                                    xtype: 'container',
                                    cls: 'button_group_video',
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: 'follow'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'Subcribe 8$'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            cls: 'col_right',
                            height: 500,
                            items: [
                                {
                                    xtype: 'container',
                                    cls: 'button_group',
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: 'Chat'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'video'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'textareafield',
                                    cls: 'chatBox',
                                    height: 340,
                                    id: 'chatBoxHistory',
                                    fieldLabel: '',
                                    name: 'chatBoxHistory',
                                    value: 'Welcome to the chat room!\n» Orogenesis: hopefully they can work as a team too\n\n» Jmickley1996: god am i the only one whos sound is terrible? like reallly choppy?\n\n» Orogenesis: sounds fine to me Ive missed winter, I like his insights great player but cant find a good team to save his life\n\n» Mod Awesome_ninja: it does crackle a bit\n\n» Psilocyboid: Winter is a horrible caster for this. Hard to understand and talks over Godz all the time\n\n» Mod Awesome_ninja: I think this is due to Twitch VODs\n\n» Orogenesis: yeah I hear what you mean now How is it hard to understand? His english vocabulary is better than most americans just a bit of an accent\n\n» Jmickley1996: DAMN YOU TWITCH\n\n» Psilocyboid: vocabulary is one thing, enunciation is another\n\n» Mod Awesome_ninja: he is also talking over skype'
                                },
                                {
                                    xtype: 'textareafield',
                                    cls: 'chatInput',
                                    id: 'chatBox',
                                    fieldLabel: '',
                                    name: 'chatBox'
                                },
                                {
                                    xtype: 'container',
                                    cls: 'button_chat',
                                    items: [
                                        {
                                            xtype: 'cycle',
                                            cls: 'button_config',
                                            text: '',
                                            menu: {
                                                xtype: 'menu',
                                                width: 120,
                                                items: [
                                                    {
                                                        xtype: 'menucheckitem',
                                                        text: 'Menu Item'
                                                    },
                                                    {
                                                        xtype: 'menucheckitem',
                                                        text: 'Menu Item'
                                                    },
                                                    {
                                                        xtype: 'menucheckitem',
                                                        text: 'Menu Item'
                                                    }
                                                ]
                                            }
                                        },
                                        {
                                            xtype: 'cycle',
                                            cls: 'button_config',
                                            menu: {
                                                xtype: 'menu',
                                                width: 120,
                                                items: [
                                                    {
                                                        xtype: 'menucheckitem',
                                                        text: 'Menu Item'
                                                    },
                                                    {
                                                        xtype: 'menucheckitem',
                                                        text: 'Menu Item'
                                                    },
                                                    {
                                                        xtype: 'menucheckitem',
                                                        text: 'Menu Item'
                                                    }
                                                ]
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            cls: 'button_chat',
                                            id: 'btnSendChat',
                                            text: 'chat'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});